INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (1, 'Sports', 'Black', 'Nike', 'Running Shoes', 9999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (2, 'Sports', 'Blue', 'Adidas', 'Football Jersey', 2999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (3, 'Sports', 'Red', 'Puma', 'Cricket Bat', 5499);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (4, 'Sports', 'Green', 'Yonex', 'Badminton Racket', 3299);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (5, 'Electronics', 'Black', 'Sony', 'Wireless Headphones', 7999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (6, 'Electronics', 'Silver', 'Samsung', 'Smartwatch', 13999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (7, 'Electronics', 'White', 'Apple', 'Bluetooth Earbuds', 17999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (8, 'Electronics', 'Grey', 'Dell', 'Wireless Keyboard', 2499);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (9, 'Fashion', 'Black', 'Levis', 'Denim Jeans', 3499);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (10, 'Fashion', 'Pink', 'H&M', 'T-Shirt', 1299);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (11, 'Fashion', 'White', 'Zara', 'Casual Shirt', 2199);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (12, 'Fashion', 'Brown', 'Woodland', 'Leather Belt', 1599);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (13, 'Furniture', 'Brown', 'IKEA', 'Wooden Chair', 4499);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (14, 'Furniture', 'White', 'Durian', 'Office Table', 7999);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (15, 'Furniture', 'Grey', 'Nilkamal', 'Plastic Cabinet', 3599);

INSERT INTO product_dtls (PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_COLOR, PRODUCT_COMPANY, PRODUCT_NAME, PRODUCT_PRICE)
VALUES (16, 'Furniture', 'Beige', 'Godrej Interio', 'Sofa Set', 25999);

